### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by lll-jy** [lll-jy/cs3245-assign2#2]
Things implemented:
1. Indexing, all done. (But may improve if you wish?)
2. Parsing query using the suggested algorithm.
3. Searching for a single word using pointer in postings file.
4. AND (skipping applied):
    a. over words
    b. over lists
5. Documentation up to this point.

Things to implement:
1. AND:
    a. divide into cases, i.e. words, lists, not_words, not_lists
    b. AND_NOT
2. OR:
    a. over words
    b. over lists
    c. combine
3. NOT:
    a. tag
    b. force open
4. Integration of all operations
5. Output to file
6. Testing

**Comment by lll-jy** [comment]
1.b done

**Comment by lll-jy** [comment]
1.a done
3. done

**Comment by Ringo1225** [comment]
2. done
